### ISSUE TITLE
mono sound

### ISSUE THREAD

**Issue by T0biasCZe** [LIJI32/GBVideoPlayer2#7]
Could you add ability to use mono sound instead of stereo?
Mono sound instead of stereo would half the audio size,
to further lower it, 2bit sound would also be nice... (since 2bit is still listenable)

**Comment by LIJI32** [comment]
Reducing the sample bit depth will not have an effect on file size. A single stereo sample is stored as a single byte, where each nibble contains either a right or left sample. Reducing the bit depth will require bit packing to actually benefit from it, and the CPU usage is too tight for this. Audio size is already extremely minimal compared to video size, being around 19 times smaller than video data (compression aside).
